# Generated by Django 3.0.5 on 2020-04-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_nowaklasa'),
        ('website', '0002_rezyser'),
    ]

    operations = [
    ]
